export type T_OPERATOR = 'MCI' | 'MTN' | 'RIGHTEL';

export type T_PROVINCE =
  | 'Tehran'
  | 'Alborz'
  | 'Isfahan'
  | 'East_Azerbaijan'
  | 'West_Azerbaijan'
  | 'Ardabil'
  | 'Bushehr'
  | 'Chaharmahal_O_Bakhtiari'
  | 'Fars'
  | 'Gilan'
  | 'Golestan'
  | 'Hamedan'
  | 'Hormozgan'
  | 'Ilam'
  | 'Kerman'
  | 'Kermanshah'
  | 'Khorasan_Razavi'
  | 'North_Khorasan'
  | 'South_Khorasan'
  | 'Khuzestan'
  | 'Kurdistan'
  | 'Lorestan'
  | 'Markazi'
  | 'Mazandaran'
  | 'Qazvin'
  | 'Qom'
  | 'Semnan'
  | 'Sistan_O_Baluchestan'
  | 'Yazd'
  | 'Zanjan';
